/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License;
 * you may not use this file except in compliance with the Elastic License.
 */
export {
  AGENT_API_ROUTES,
  AGENT_CONFIG_API_ROUTES,
  AGENT_CONFIG_SAVED_OBJECT_TYPE,
  // Saved object types
  AGENT_EVENT_SAVED_OBJECT_TYPE,
  AGENT_POLLING_INTERVAL,
  AGENT_POLLING_THRESHOLD_MS,
  AGENT_SAVED_OBJECT_TYPE,
  AGENT_TYPE_EPHEMERAL,
  AGENT_TYPE_PERMANENT,
  AGENT_TYPE_TEMPORARY,
  DATASOURCE_API_ROUTES,
  DATASOURCE_SAVED_OBJECT_TYPE,
  // Defaults
  DEFAULT_AGENT_CONFIG,
  DEFAULT_OUTPUT,
  ENROLLMENT_API_KEYS_SAVED_OBJECT_TYPE,
  ENROLLMENT_API_KEY_ROUTES,
  EPM_API_ROUTES,
  FLEET_SETUP_API_ROUTES,
  INDEX_PATTERN_SAVED_OBJECT_TYPE,
  INSTALL_SCRIPT_API_ROUTES,
  OUTPUT_SAVED_OBJECT_TYPE,
  PACKAGES_SAVED_OBJECT_TYPE,
  // Routes
  PLUGIN_ID,
  SETUP_API_ROUTE,
} from '../../common';
